package org.cic.template.persistent.mybatis.tftis.model;

import java.io.Serializable;
import java.util.Date;

public class Apuser implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APUSER.USER_ID
     *
     * @mbg.generated Wed Aug 09 19:21:51 CST 2017
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APUSER.USER_NAME
     *
     * @mbg.generated Wed Aug 09 19:21:51 CST 2017
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APUSER.PWD
     *
     * @mbg.generated Wed Aug 09 19:21:51 CST 2017
     */
    private String pwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APUSER.GROUP_NO
     *
     * @mbg.generated Wed Aug 09 19:21:51 CST 2017
     */
    private String groupNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APUSER.UPOWER
     *
     * @mbg.generated Wed Aug 09 19:21:51 CST 2017
     */
    private String upower;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APUSER.CREATE_DATE
     *
     * @mbg.generated Wed Aug 09 19:21:51 CST 2017
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APUSER.REMARKS
     *
     * @mbg.generated Wed Aug 09 19:21:51 CST 2017
     */
    private String remarks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APUSER.UPD_ID
     *
     * @mbg.generated Wed Aug 09 19:21:51 CST 2017
     */
    private String updId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APUSER.UPD_DATE
     *
     * @mbg.generated Wed Aug 09 19:21:51 CST 2017
     */
    private Date updDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APUSER.EMP_ID
     *
     * @mbg.generated Wed Aug 09 19:21:51 CST 2017
     */
    private String empId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APUSER.SET_NO
     *
     * @mbg.generated Wed Aug 09 19:21:51 CST 2017
     */
    private String setNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APUSER.AGENT_ID
     *
     * @mbg.generated Wed Aug 09 19:21:51 CST 2017
     */
    private String agentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APUSER.NATIONALITY
     *
     * @mbg.generated Wed Aug 09 19:21:51 CST 2017
     */
    private String nationality;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APUSER.IS_TODO
     *
     * @mbg.generated Wed Aug 09 19:21:51 CST 2017
     */
    private String isTodo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table APUSER
     *
     * @mbg.generated Wed Aug 09 19:21:51 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APUSER.USER_ID
     *
     * @return the value of APUSER.USER_ID
     *
     * @mbg.generated Wed Aug 09 19:21:51 CST 2017
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APUSER.USER_ID
     *
     * @param userId the value for APUSER.USER_ID
     *
     * @mbg.generated Wed Aug 09 19:21:51 CST 2017
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APUSER.USER_NAME
     *
     * @return the value of APUSER.USER_NAME
     *
     * @mbg.generated Wed Aug 09 19:21:51 CST 2017
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APUSER.USER_NAME
     *
     * @param userName the value for APUSER.USER_NAME
     *
     * @mbg.generated Wed Aug 09 19:21:51 CST 2017
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APUSER.PWD
     *
     * @return the value of APUSER.PWD
     *
     * @mbg.generated Wed Aug 09 19:21:51 CST 2017
     */
    public String getPwd() {
        return pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APUSER.PWD
     *
     * @param pwd the value for APUSER.PWD
     *
     * @mbg.generated Wed Aug 09 19:21:51 CST 2017
     */
    public void setPwd(String pwd) {
        this.pwd = pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APUSER.GROUP_NO
     *
     * @return the value of APUSER.GROUP_NO
     *
     * @mbg.generated Wed Aug 09 19:21:51 CST 2017
     */
    public String getGroupNo() {
        return groupNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APUSER.GROUP_NO
     *
     * @param groupNo the value for APUSER.GROUP_NO
     *
     * @mbg.generated Wed Aug 09 19:21:51 CST 2017
     */
    public void setGroupNo(String groupNo) {
        this.groupNo = groupNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APUSER.UPOWER
     *
     * @return the value of APUSER.UPOWER
     *
     * @mbg.generated Wed Aug 09 19:21:51 CST 2017
     */
    public String getUpower() {
        return upower;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APUSER.UPOWER
     *
     * @param upower the value for APUSER.UPOWER
     *
     * @mbg.generated Wed Aug 09 19:21:51 CST 2017
     */
    public void setUpower(String upower) {
        this.upower = upower;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APUSER.CREATE_DATE
     *
     * @return the value of APUSER.CREATE_DATE
     *
     * @mbg.generated Wed Aug 09 19:21:51 CST 2017
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APUSER.CREATE_DATE
     *
     * @param createDate the value for APUSER.CREATE_DATE
     *
     * @mbg.generated Wed Aug 09 19:21:51 CST 2017
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APUSER.REMARKS
     *
     * @return the value of APUSER.REMARKS
     *
     * @mbg.generated Wed Aug 09 19:21:51 CST 2017
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APUSER.REMARKS
     *
     * @param remarks the value for APUSER.REMARKS
     *
     * @mbg.generated Wed Aug 09 19:21:51 CST 2017
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APUSER.UPD_ID
     *
     * @return the value of APUSER.UPD_ID
     *
     * @mbg.generated Wed Aug 09 19:21:51 CST 2017
     */
    public String getUpdId() {
        return updId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APUSER.UPD_ID
     *
     * @param updId the value for APUSER.UPD_ID
     *
     * @mbg.generated Wed Aug 09 19:21:51 CST 2017
     */
    public void setUpdId(String updId) {
        this.updId = updId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APUSER.UPD_DATE
     *
     * @return the value of APUSER.UPD_DATE
     *
     * @mbg.generated Wed Aug 09 19:21:51 CST 2017
     */
    public Date getUpdDate() {
        return updDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APUSER.UPD_DATE
     *
     * @param updDate the value for APUSER.UPD_DATE
     *
     * @mbg.generated Wed Aug 09 19:21:51 CST 2017
     */
    public void setUpdDate(Date updDate) {
        this.updDate = updDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APUSER.EMP_ID
     *
     * @return the value of APUSER.EMP_ID
     *
     * @mbg.generated Wed Aug 09 19:21:51 CST 2017
     */
    public String getEmpId() {
        return empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APUSER.EMP_ID
     *
     * @param empId the value for APUSER.EMP_ID
     *
     * @mbg.generated Wed Aug 09 19:21:51 CST 2017
     */
    public void setEmpId(String empId) {
        this.empId = empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APUSER.SET_NO
     *
     * @return the value of APUSER.SET_NO
     *
     * @mbg.generated Wed Aug 09 19:21:51 CST 2017
     */
    public String getSetNo() {
        return setNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APUSER.SET_NO
     *
     * @param setNo the value for APUSER.SET_NO
     *
     * @mbg.generated Wed Aug 09 19:21:51 CST 2017
     */
    public void setSetNo(String setNo) {
        this.setNo = setNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APUSER.AGENT_ID
     *
     * @return the value of APUSER.AGENT_ID
     *
     * @mbg.generated Wed Aug 09 19:21:51 CST 2017
     */
    public String getAgentId() {
        return agentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APUSER.AGENT_ID
     *
     * @param agentId the value for APUSER.AGENT_ID
     *
     * @mbg.generated Wed Aug 09 19:21:51 CST 2017
     */
    public void setAgentId(String agentId) {
        this.agentId = agentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APUSER.NATIONALITY
     *
     * @return the value of APUSER.NATIONALITY
     *
     * @mbg.generated Wed Aug 09 19:21:51 CST 2017
     */
    public String getNationality() {
        return nationality;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APUSER.NATIONALITY
     *
     * @param nationality the value for APUSER.NATIONALITY
     *
     * @mbg.generated Wed Aug 09 19:21:51 CST 2017
     */
    public void setNationality(String nationality) {
        this.nationality = nationality;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APUSER.IS_TODO
     *
     * @return the value of APUSER.IS_TODO
     *
     * @mbg.generated Wed Aug 09 19:21:51 CST 2017
     */
    public String getIsTodo() {
        return isTodo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APUSER.IS_TODO
     *
     * @param isTodo the value for APUSER.IS_TODO
     *
     * @mbg.generated Wed Aug 09 19:21:51 CST 2017
     */
    public void setIsTodo(String isTodo) {
        this.isTodo = isTodo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APUSER
     *
     * @mbg.generated Wed Aug 09 19:21:51 CST 2017
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Apuser other = (Apuser) that;
        return (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getUserName() == null ? other.getUserName() == null : this.getUserName().equals(other.getUserName()))
            && (this.getPwd() == null ? other.getPwd() == null : this.getPwd().equals(other.getPwd()))
            && (this.getGroupNo() == null ? other.getGroupNo() == null : this.getGroupNo().equals(other.getGroupNo()))
            && (this.getUpower() == null ? other.getUpower() == null : this.getUpower().equals(other.getUpower()))
            && (this.getCreateDate() == null ? other.getCreateDate() == null : this.getCreateDate().equals(other.getCreateDate()))
            && (this.getRemarks() == null ? other.getRemarks() == null : this.getRemarks().equals(other.getRemarks()))
            && (this.getUpdId() == null ? other.getUpdId() == null : this.getUpdId().equals(other.getUpdId()))
            && (this.getUpdDate() == null ? other.getUpdDate() == null : this.getUpdDate().equals(other.getUpdDate()))
            && (this.getEmpId() == null ? other.getEmpId() == null : this.getEmpId().equals(other.getEmpId()))
            && (this.getSetNo() == null ? other.getSetNo() == null : this.getSetNo().equals(other.getSetNo()))
            && (this.getAgentId() == null ? other.getAgentId() == null : this.getAgentId().equals(other.getAgentId()))
            && (this.getNationality() == null ? other.getNationality() == null : this.getNationality().equals(other.getNationality()))
            && (this.getIsTodo() == null ? other.getIsTodo() == null : this.getIsTodo().equals(other.getIsTodo()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APUSER
     *
     * @mbg.generated Wed Aug 09 19:21:51 CST 2017
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getUserName() == null) ? 0 : getUserName().hashCode());
        result = prime * result + ((getPwd() == null) ? 0 : getPwd().hashCode());
        result = prime * result + ((getGroupNo() == null) ? 0 : getGroupNo().hashCode());
        result = prime * result + ((getUpower() == null) ? 0 : getUpower().hashCode());
        result = prime * result + ((getCreateDate() == null) ? 0 : getCreateDate().hashCode());
        result = prime * result + ((getRemarks() == null) ? 0 : getRemarks().hashCode());
        result = prime * result + ((getUpdId() == null) ? 0 : getUpdId().hashCode());
        result = prime * result + ((getUpdDate() == null) ? 0 : getUpdDate().hashCode());
        result = prime * result + ((getEmpId() == null) ? 0 : getEmpId().hashCode());
        result = prime * result + ((getSetNo() == null) ? 0 : getSetNo().hashCode());
        result = prime * result + ((getAgentId() == null) ? 0 : getAgentId().hashCode());
        result = prime * result + ((getNationality() == null) ? 0 : getNationality().hashCode());
        result = prime * result + ((getIsTodo() == null) ? 0 : getIsTodo().hashCode());
        return result;
    }
}