package org.cic.template.persistent.mybatis.tftis.model;

import java.io.Serializable;
import java.util.Date;

public class NoviolationStatusLog implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column NOVIOLATION_STATUS_LOG.ID
	 * @mbg.generated  Thu Aug 17 15:14:27 CST 2017
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column NOVIOLATION_STATUS_LOG.NVNO
	 * @mbg.generated  Thu Aug 17 15:14:27 CST 2017
	 */
	private String nvno;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column NOVIOLATION_STATUS_LOG.USER_GROUP_NO
	 * @mbg.generated  Thu Aug 17 15:14:27 CST 2017
	 */
	private String userGroupNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column NOVIOLATION_STATUS_LOG.MSG
	 * @mbg.generated  Thu Aug 17 15:14:27 CST 2017
	 */
	private String msg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column NOVIOLATION_STATUS_LOG.REMARKS
	 * @mbg.generated  Thu Aug 17 15:14:27 CST 2017
	 */
	private String remarks;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column NOVIOLATION_STATUS_LOG.CREATE_ID
	 * @mbg.generated  Thu Aug 17 15:14:27 CST 2017
	 */
	private String createId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column NOVIOLATION_STATUS_LOG.CREATE_NAME
	 * @mbg.generated  Thu Aug 17 15:14:27 CST 2017
	 */
	private String createName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column NOVIOLATION_STATUS_LOG.CREATE_DATE
	 * @mbg.generated  Thu Aug 17 15:14:27 CST 2017
	 */
	private Date createDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column NOVIOLATION_STATUS_LOG.FLOW_TYPE
	 * @mbg.generated  Thu Aug 17 15:14:27 CST 2017
	 */
	private String flowType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table NOVIOLATION_STATUS_LOG
	 * @mbg.generated  Thu Aug 17 15:14:27 CST 2017
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column NOVIOLATION_STATUS_LOG.ID
	 * @return  the value of NOVIOLATION_STATUS_LOG.ID
	 * @mbg.generated  Thu Aug 17 15:14:27 CST 2017
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column NOVIOLATION_STATUS_LOG.ID
	 * @param id  the value for NOVIOLATION_STATUS_LOG.ID
	 * @mbg.generated  Thu Aug 17 15:14:27 CST 2017
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column NOVIOLATION_STATUS_LOG.NVNO
	 * @return  the value of NOVIOLATION_STATUS_LOG.NVNO
	 * @mbg.generated  Thu Aug 17 15:14:27 CST 2017
	 */
	public String getNvno() {
		return nvno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column NOVIOLATION_STATUS_LOG.NVNO
	 * @param nvno  the value for NOVIOLATION_STATUS_LOG.NVNO
	 * @mbg.generated  Thu Aug 17 15:14:27 CST 2017
	 */
	public void setNvno(String nvno) {
		this.nvno = nvno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column NOVIOLATION_STATUS_LOG.USER_GROUP_NO
	 * @return  the value of NOVIOLATION_STATUS_LOG.USER_GROUP_NO
	 * @mbg.generated  Thu Aug 17 15:14:27 CST 2017
	 */
	public String getUserGroupNo() {
		return userGroupNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column NOVIOLATION_STATUS_LOG.USER_GROUP_NO
	 * @param userGroupNo  the value for NOVIOLATION_STATUS_LOG.USER_GROUP_NO
	 * @mbg.generated  Thu Aug 17 15:14:27 CST 2017
	 */
	public void setUserGroupNo(String userGroupNo) {
		this.userGroupNo = userGroupNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column NOVIOLATION_STATUS_LOG.MSG
	 * @return  the value of NOVIOLATION_STATUS_LOG.MSG
	 * @mbg.generated  Thu Aug 17 15:14:27 CST 2017
	 */
	public String getMsg() {
		return msg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column NOVIOLATION_STATUS_LOG.MSG
	 * @param msg  the value for NOVIOLATION_STATUS_LOG.MSG
	 * @mbg.generated  Thu Aug 17 15:14:27 CST 2017
	 */
	public void setMsg(String msg) {
		this.msg = msg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column NOVIOLATION_STATUS_LOG.REMARKS
	 * @return  the value of NOVIOLATION_STATUS_LOG.REMARKS
	 * @mbg.generated  Thu Aug 17 15:14:27 CST 2017
	 */
	public String getRemarks() {
		return remarks;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column NOVIOLATION_STATUS_LOG.REMARKS
	 * @param remarks  the value for NOVIOLATION_STATUS_LOG.REMARKS
	 * @mbg.generated  Thu Aug 17 15:14:27 CST 2017
	 */
	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column NOVIOLATION_STATUS_LOG.CREATE_ID
	 * @return  the value of NOVIOLATION_STATUS_LOG.CREATE_ID
	 * @mbg.generated  Thu Aug 17 15:14:27 CST 2017
	 */
	public String getCreateId() {
		return createId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column NOVIOLATION_STATUS_LOG.CREATE_ID
	 * @param createId  the value for NOVIOLATION_STATUS_LOG.CREATE_ID
	 * @mbg.generated  Thu Aug 17 15:14:27 CST 2017
	 */
	public void setCreateId(String createId) {
		this.createId = createId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column NOVIOLATION_STATUS_LOG.CREATE_NAME
	 * @return  the value of NOVIOLATION_STATUS_LOG.CREATE_NAME
	 * @mbg.generated  Thu Aug 17 15:14:27 CST 2017
	 */
	public String getCreateName() {
		return createName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column NOVIOLATION_STATUS_LOG.CREATE_NAME
	 * @param createName  the value for NOVIOLATION_STATUS_LOG.CREATE_NAME
	 * @mbg.generated  Thu Aug 17 15:14:27 CST 2017
	 */
	public void setCreateName(String createName) {
		this.createName = createName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column NOVIOLATION_STATUS_LOG.CREATE_DATE
	 * @return  the value of NOVIOLATION_STATUS_LOG.CREATE_DATE
	 * @mbg.generated  Thu Aug 17 15:14:27 CST 2017
	 */
	public Date getCreateDate() {
		return createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column NOVIOLATION_STATUS_LOG.CREATE_DATE
	 * @param createDate  the value for NOVIOLATION_STATUS_LOG.CREATE_DATE
	 * @mbg.generated  Thu Aug 17 15:14:27 CST 2017
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column NOVIOLATION_STATUS_LOG.FLOW_TYPE
	 * @return  the value of NOVIOLATION_STATUS_LOG.FLOW_TYPE
	 * @mbg.generated  Thu Aug 17 15:14:27 CST 2017
	 */
	public String getFlowType() {
		return flowType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column NOVIOLATION_STATUS_LOG.FLOW_TYPE
	 * @param flowType  the value for NOVIOLATION_STATUS_LOG.FLOW_TYPE
	 * @mbg.generated  Thu Aug 17 15:14:27 CST 2017
	 */
	public void setFlowType(String flowType) {
		this.flowType = flowType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table NOVIOLATION_STATUS_LOG
	 * @mbg.generated  Thu Aug 17 15:14:27 CST 2017
	 */@Override public boolean equals(Object that){if (this == that){return true;}if (that == null){return false;}if (getClass() != that.getClass()){return false;}NoviolationStatusLog other=(NoviolationStatusLog)that;return (this.getId() == null?other.getId() == null:this.getId().equals(other.getId())) && (this.getNvno() == null?other.getNvno() == null:this.getNvno().equals(other.getNvno())) && (this.getUserGroupNo() == null?other.getUserGroupNo() == null:this.getUserGroupNo().equals(other.getUserGroupNo())) && (this.getMsg() == null?other.getMsg() == null:this.getMsg().equals(other.getMsg())) && (this.getRemarks() == null?other.getRemarks() == null:this.getRemarks().equals(other.getRemarks())) && (this.getCreateId() == null?other.getCreateId() == null:this.getCreateId().equals(other.getCreateId())) && (this.getCreateName() == null?other.getCreateName() == null:this.getCreateName().equals(other.getCreateName())) && (this.getCreateDate() == null?other.getCreateDate() == null:this.getCreateDate().equals(other.getCreateDate())) && (this.getFlowType() == null?other.getFlowType() == null:this.getFlowType().equals(other.getFlowType()));}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table NOVIOLATION_STATUS_LOG
	 * @mbg.generated  Thu Aug 17 15:14:27 CST 2017
	 */@Override public int hashCode(){final int prime=31;int result=1;result=prime * result + ((getId() == null)?0:getId().hashCode());result=prime * result + ((getNvno() == null)?0:getNvno().hashCode());result=prime * result + ((getUserGroupNo() == null)?0:getUserGroupNo().hashCode());result=prime * result + ((getMsg() == null)?0:getMsg().hashCode());result=prime * result + ((getRemarks() == null)?0:getRemarks().hashCode());result=prime * result + ((getCreateId() == null)?0:getCreateId().hashCode());result=prime * result + ((getCreateName() == null)?0:getCreateName().hashCode());result=prime * result + ((getCreateDate() == null)?0:getCreateDate().hashCode());result=prime * result + ((getFlowType() == null)?0:getFlowType().hashCode());return result;}


}