package org.cic.template.persistent.mybatis.tftis.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.cic.template.persistent.mybatis.tftis.model.NoviolationStatusLog;
import org.cic.template.persistent.mybatis.tftis.model.NoviolationStatusLogCriteria;
import org.cic.template.persistent.mybatis.tftis.model.NoviolationStatusLogEntity;

public interface NoviolationStatusLogMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table NOVIOLATION_STATUS_LOG
	 * @mbg.generated  Thu Aug 17 15:14:27 CST 2017
	 */
	long countByExample(NoviolationStatusLogCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table NOVIOLATION_STATUS_LOG
	 * @mbg.generated  Thu Aug 17 15:14:27 CST 2017
	 */
	int deleteByExample(NoviolationStatusLogCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table NOVIOLATION_STATUS_LOG
	 * @mbg.generated  Thu Aug 17 15:14:27 CST 2017
	 */
	int insert(NoviolationStatusLog record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table NOVIOLATION_STATUS_LOG
	 * @mbg.generated  Thu Aug 17 15:14:27 CST 2017
	 */
	int insertSelective(NoviolationStatusLog record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table NOVIOLATION_STATUS_LOG
	 * @mbg.generated  Thu Aug 17 15:14:27 CST 2017
	 */List<NoviolationStatusLog> selectByExample(NoviolationStatusLogCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table NOVIOLATION_STATUS_LOG
	 * @mbg.generated  Thu Aug 17 15:14:27 CST 2017
	 */int updateByExampleSelective(@Param("record") NoviolationStatusLog record,@Param("example") NoviolationStatusLogCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table NOVIOLATION_STATUS_LOG
	 * @mbg.generated  Thu Aug 17 15:14:27 CST 2017
	 */int updateByExample(@Param("record") NoviolationStatusLog record,@Param("example") NoviolationStatusLogCriteria example);
	 
	 Integer countByCond(NoviolationStatusLogEntity record);
	 
	 List<NoviolationStatusLog> selectByCond(NoviolationStatusLogEntity record);

}